(define (f x y z) (cond ((and (<= x y) (<= x z)) (+ (* y y) (* z z)))
                        ((and (<= y x) (<= y z)) (+ (* x x) (* z z)))
                        ((and (<= z x) (<= z y)) (+ (* x x) (* y y)))
                  )
)
(f 1 2 3)
(f 2 1 3)
(f 2 3 1)
(f -1 -2 -3)
(f -2 -1 -3)
(f -2 -3 -1)
(f 1 1 1)
